# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image_loader2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 531, 601))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Image_label = QtWidgets.QLabel(self.widget)
        self.Image_label.setText("")
        self.Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_label.setObjectName("Image_label")
        self.gridLayout.addWidget(self.Image_label, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.PreviousButton = QtWidgets.QPushButton(self.widget)
        self.PreviousButton.setObjectName("PreviousButton")
        self.gridLayout.addWidget(self.PreviousButton, 1, 1, 1, 1)
        self.NextButton = QtWidgets.QPushButton(self.widget)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout.addWidget(self.NextButton, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 548, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionFolder)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionClose)
        self.menuBar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PreviousButton.setText(_translate("MainWindow", "<"))
        self.NextButton.setText(_translate("MainWindow", ">"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionFile.setText(_translate("MainWindow", "Open"))
        self.actionFolder.setText(_translate("MainWindow", "Open Folder"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
