# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image_loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 2, 2, 1, 1)
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout.addWidget(self.NextButton, 2, 0, 1, 1)
        self.CloseButton = QtWidgets.QPushButton(self.centralwidget)
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout.addWidget(self.CloseButton, 2, 3, 1, 1)
        self.PreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousButton.setObjectName("PreviousButton")
        self.gridLayout.addWidget(self.PreviousButton, 2, 1, 1, 1)
        self.Image_label = QtWidgets.QLabel(self.centralwidget)
        self.Image_label.setText("")
        self.Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_label.setObjectName("Image_label")
        self.gridLayout.addWidget(self.Image_label, 0, 0, 2, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 532, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.menuOpen.addAction(self.actionFile)
        self.menuOpen.addAction(self.actionFolder)
        self.menuBar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        self.CloseButton.setText(_translate("MainWindow", "Close"))
        self.PreviousButton.setText(_translate("MainWindow", "Previous"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
