# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Label.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Label(object):
    def setupUi(self, Label):
        Label.setObjectName("Label")
        Label.resize(340, 191)
        self.Path_label = QtWidgets.QLabel(Label)
        self.Path_label.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.Path_label.setMaximumSize(QtCore.QSize(41, 21))
        self.Path_label.setObjectName("Path_label")
        self.Path_line = QtWidgets.QLineEdit(Label)
        self.Path_line.setGeometry(QtCore.QRect(60, 20, 241, 23))
        self.Path_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Path_line.setObjectName("Path_line")
        self.toolButton = QtWidgets.QToolButton(Label)
        self.toolButton.setGeometry(QtCore.QRect(308, 20, 24, 22))
        self.toolButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolButton.setObjectName("toolButton")
        self.groupBox = QtWidgets.QGroupBox(Label)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 201, 121))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Green = QtWidgets.QPushButton(self.groupBox)
        self.Green.setGeometry(QtCore.QRect(15, 9, 22, 22))
        self.Green.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Green.setAutoFillBackground(True)
        self.Green.setStyleSheet("")
        self.Green.setText("")
        self.Green.setObjectName("Green")
        self.Blue = QtWidgets.QPushButton(self.groupBox)
        self.Blue.setGeometry(QtCore.QRect(15, 89, 22, 22))
        self.Blue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Blue.setAcceptDrops(False)
        self.Blue.setAutoFillBackground(True)
        self.Blue.setText("")
        self.Blue.setObjectName("Blue")
        self.Green_line = QtWidgets.QLineEdit(self.groupBox)
        self.Green_line.setGeometry(QtCore.QRect(60, 10, 113, 21))
        self.Green_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.Green_line.setObjectName("Green_line")
        self.Yellow = QtWidgets.QPushButton(self.groupBox)
        self.Yellow.setGeometry(QtCore.QRect(15, 49, 22, 22))
        self.Yellow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Yellow.setAutoFillBackground(True)
        self.Yellow.setText("")
        self.Yellow.setObjectName("Yellow")
        self.Blue_line = QtWidgets.QLineEdit(self.groupBox)
        self.Blue_line.setGeometry(QtCore.QRect(60, 90, 113, 21))
        self.Blue_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.Blue_line.setObjectName("Blue_line")
        self.Yellow_line = QtWidgets.QLineEdit(self.groupBox)
        self.Yellow_line.setGeometry(QtCore.QRect(60, 50, 113, 21))
        self.Yellow_line.setMaximumSize(QtCore.QSize(16777215, 21))
        self.Yellow_line.setObjectName("Yellow_line")
        self.Save_Button = QtWidgets.QPushButton(Label)
        self.Save_Button.setGeometry(QtCore.QRect(245, 145, 81, 32))
        self.Save_Button.setObjectName("Save_Button")

        self.retranslateUi(Label)
        QtCore.QMetaObject.connectSlotsByName(Label)

    def retranslateUi(self, Label):
        _translate = QtCore.QCoreApplication.translate
        Label.setWindowTitle(_translate("Label", "Dialog"))
        self.Path_label.setText(_translate("Label", "Path :"))
        self.toolButton.setText(_translate("Label", "..."))
        self.Save_Button.setText(_translate("Label", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Label = QtWidgets.QDialog()
    ui = Ui_Label()
    ui.setupUi(Label)
    Label.show()
    sys.exit(app.exec_())
